inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - sequel-batches.gemspec

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  Enabled: false
